version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "security"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "-"
  
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "security"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "-"
